force-app/main/default/objects/Species__c/fields/Winter_Watering_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Winter_Watering_Frequency__c</fullName>
    <label>Winter Watering Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every three months</fullName>
            </value>
            <value>
                <fullName>Not needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FrequencyServiceTest.cls
@isTest
private with sharing class FrequencyServiceTest {
  @isTest
  // metodoTesteado_casoDeUso_ResultadoEsperado
  static void getWateringDays_wateringFreqDailyAndSummer_oneDay() {
    // GIVEN -- Creación de datos, escenario, etc...
    Species__c specie = new Species__c();
    specie.winter_Watering_Frequency__c = 'Daily';

    // WHEN -- Llamamos al método
    Integer days = FrequencyService.getWateringDays(specie);

    // THEN -- Chequear el resultado esperado
    Integer expectedDays = 1;
    System.assertEquals(expectedDays, days, '1 day returned');
  }

  //TODO agregar el resto de las pruebas unitarias. Weekly - Summer / Winter , twice per week etc etc
}